name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm install      

      - name: Run tests
        run: npm test
        env:
          CI: true

  sonarcloud:

    runs-on: ubuntu-latest
    needs: run-ci  # Makes sonarcloud dependent on successful completion of the build job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.1'  # Specify Node.js version to match the build job environment
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Test
      run: go test -coverprofile=coverage.out

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   